apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Der Name der ClusterRole für KubeVirt
  name: kubevirt-argocd-role
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - get
  - list
  - update
  - delete

